<?php

global $_LANGMAIL;
$_LANGMAIL = array();

$_LANGMAIL['Newsletter confirmation'] = 'אישור רישום לניוזלטר';
$_LANGMAIL['Email verification'] = 'אימות מייל';
$_LANGMAIL['Newsletter voucher'] = 'שובר ניוזלטר';
$_LANGMAIL['Your wishlist\\\'s link'] = 'קישור לרשימת החלומות שלך';
$_LANGMAIL['Message from %1$s %2$s'] = 'הודעה מאת %1$s %2$s';
$_LANGMAIL['Your cart and your discount'] = 'העגלה וההנחות שלך';
$_LANGMAIL['Thanks for your order'] = 'תודה על הזמנתך';
$_LANGMAIL['You are one of our best customers'] = 'את/ה אחד הלקוחות הטובים שלנו';
$_LANGMAIL['We miss you'] = 'מתגעגעים אליך';
$_LANGMAIL['Product available'] = 'המוצר זמין';
$_LANGMAIL['Stock coverage'] = 'כיסוי מלאי';
$_LANGMAIL['Product out of stock'] = 'המוצר אזל מהמלאי';
$_LANGMAIL['Congratulations!'] = 'מזל טוב!';
$_LANGMAIL['%1$s sent you a link to %2$s'] = '%1$s שלח לך קישור אל %2$s';
$_LANGMAIL['Welcome!'] = 'ברוך הבא לאתר  {shop_name}';
$_LANGMAIL['Process the payment of your order'] = 'אנא השלם את התשלום עבור ההזמנה';
$_LANGMAIL['Your message has been correctly sent #ct%1$s #tc%2$s'] = 'הודעתך נשלחה בהצלחה #ct%1$s #tc%2$s';
$_LANGMAIL['Your message has been correctly sent'] = 'הודעתך נשלחה בהצלחה';
$_LANGMAIL['Message from contact form'] = 'חנות {shop_name} - הודעה מטופס צור קשר';
$_LANGMAIL['New credit slip regarding your order'] = 'שובר זיכוי חדש ממתין לך באתר {shop_name}';
$_LANGMAIL['Virtual product to download'] = 'מוצר להורדה';
$_LANGMAIL['Fwd: Customer message'] = 'העברה: הודעת לקוח מאת {employee}';
$_LANGMAIL['Your guest account has been transformed to customer account'] = 'חשבון האורח שלך שודרג לחשבון לקוח';
$_LANGMAIL['Package in transit'] = 'עדכון לגבי משלוח החבילה מאתר {shop_name}';
$_LANGMAIL['Log: You have a new alert from your shop'] = 'לוג: קיבלת התראה חדשה מחנות {shop_name}';
$_LANGMAIL['Your order has been changed'] = 'עדכון לגבי שינוי בהזמנתך מחנות {shop_name}';
$_LANGMAIL['Order confirmation'] = 'אישור הזמנה מאתר {shop_name}';
$_LANGMAIL['Message from a customer'] = 'הודעה מלקוח באתר {shop_name}';
$_LANGMAIL['New message regarding your order'] = 'אתר {shop_name} - הודעה חדשה לגבי הזמנתך';
$_LANGMAIL['Your order return state has changed'] = 'אתר {shop_name} - עדכון לגבי מצב החזרת הזמנתך';
$_LANGMAIL['Your new password'] = 'הודעה מאתר {shop_name} - פרטי התחברות מעודכנים';
$_LANGMAIL['Password query confirmation'] = 'אישור איפוס סיסמא - אתר {shop_name}';
$_LANGMAIL['An answer to your message is available #ct%1$s #tc%2$s'] = 'אתר {shop_name} - תשובה לשאלתך #ct%1$s #tc%2$s';
$_LANGMAIL['New voucher regarding your order %s'] = 'אתר {shop_name} - הנפקת שובר חדש להזמנתך %s';
$_LANGMAIL['New order - #%06d'] = 'הזמנה חדשה - #%06d';
